.TH ix 8 User Manuals
.SH NAME
ix \- Inode Attributes
.SH SYNOPSIS
\fBix -get-attr \fIfile\fB

ix -set-attr \fIfile\fB \fIlist\fB

ix -get-xid \fIfile\fB

ix -set-xid \fIfile\fB \fIxid\fB
\f1
.SH DESCRIPTION
This tool is used to set filesystem attributes specific to Linux-VServer.

The attributes belong to four categories:

- xid tagging

- procfs security

- chroot barrier

- copy-on-write immutable link breaking
.SH OPTIONS
.TP
\fB-get-attr\f1
Get attributes of \fIfile\f1. See below for valid attributes.
.TP
\fB-set-attr\f1
Set attributes of \fIfile\f1. See below for valid attributes.
.TP
\fB-get-xid\f1
Get context id of \fIfile\f1.
.TP
\fB-set-xid\f1
Set context id of \fIfile\f1 to \fIxid\f1.
.SH VALID ATTRIBUTES
TAG - file is xid tagged (xid tagging)

ADMIN - accessible in xid=0 (procfs security)

WATCH - accessible in xid=1 (procfs security)

HIDE - not accessible in xid!=(0|1) (procfs security)

BARRIER - directory barrier (chroot barrier)

IUNLINK - unlink file (cow link breaking)

IMMUTABLE - file is immutable (cow link breaking)
.SH AUTHOR
ix was written by Benedikt Boehm <hollow@gentoo.org>

You will find the newest version of dx in the libvserver package at \fBhttp://linux-vserver.org\f1. There is also a mailing list, you will find information about it at Linux-VServer main site.
.SH BUGS
You should report them to the mailing list.
.SH SEE ALSO
\fBdx(8)\f1, \fBns(8)\f1, \fBnx(8)\f1, \fBvr(8)\f1, \fBvx(8)\f1
