.TH ns 8 User Manuals
.SH NAME
ns \- Filesystem Namespaces
.SH SYNOPSIS
\fBns -create \fIxid\fB

ns -migrate \fIxid\fB -- \fIprogram\fB \fIargs*\fB
\f1
.SH DESCRIPTION
A recent addition to the Linux-VServer branch was the introduction of Private Namespaces. This uses the already existing Virtual Filesystem Layer of the Linux kernel to create a separate view of the filesystem for the processes belonging to a context.

The major advantage over the shared namespace used by default is that any modifications to the namespace layout (like mounts) do not affect other contexts, not even the Host Context.
.SH OPTIONS
.TP
\fB-create\f1
Create a new filesystem namespace and assign it to context \fIxid\f1.
.TP
\fB-migrate\f1
Migrate to filesystem namespace of context \fIxid\f1 and execute \fIprogram\f1 with \fIargs*\f1.
.SH AUTHOR
ns was written by Benedikt Boehm <hollow@gentoo.org>

You will find the newest version of dx in the libvserver package at \fBhttp://linux-vserver.org\f1. There is also a mailing list, you will find information about it at Linux-VServer main site.
.SH BUGS
You should report them to the mailing list.
.SH SEE ALSO
\fBdx(8)\f1, \fBix(8)\f1, \fBnx(8)\f1, \fBvr(8)\f1, \fBvx(8)\f1, 
