.TH nx 8 User Manuals
.SH NAME
nx \- Network Context Setup
.SH SYNOPSIS
\fBnx -create \fInid\fB [\fIlist\fB] [-- \fIprogram\fB \fIargs\fB*]

nx -migrate \fInid\fB -- \fIprogram\fB \fIargs\fB*

nx -set-flags \fInid\fB \fIlist\fB

nx -get-flags \fInid\fB

nx -add-addr \fInid\fB \fIaddr\fB/\fInetmask\fB*

nx -rem-addr \fInid\fB \fIaddr\fB/\fInetmask\fB*
\f1
.SH DESCRIPTION
While the Context Separation is sufficient to isolate groups of processes, a different kind of separation, or rather a limitation, is required to confine processes to a subset of available network addresses.

Several issues have to be considered when doing so; for example, the fact that bindings to special addresses like IPADDR_ANY or the local host address have to be handled in a very special way.

Currently, Linux-VServer doesn't make use of virtual network devices (and maybe never will) to minimize the resulting overhead. Therefore socket binding and packet transmission have been adjusted.
.SH OPTIONS
.TP
\fB-create\f1
Create a new network context with id \fInid\f1 using optional flags in \fIlist\f1 and optionally run \fIprogram\f1 in the new context.
.TP
\fB-migrate\f1
Migrate to network context \fInid\f1 and execute \fIprogram\f1.
.TP
\fB-set-flags\f1
Set context flags in \fIlist\f1 for network context \fInid\f1. See below for valid flags.
.TP
\fB-get-flags\f1
Get flags for network context \fInid\f1. See below for valid flags.
.TP
\fB-add-addr\f1
Add IP address \fIaddr\f1/\fInetmask\f1 to network context \fInid\f1. More than one IP address can be specified.
.TP
\fB-rem-addr\f1
Remove IP address \fIaddr\f1/\fInetmask\f1 from network context \fInid\f1. More than one IP address can be specified.
.SH VALID FLAGS
STATE_SETUP - network context is in setup state

SC_HELPER - network state change helper

PERSISTENT - make network context persistent
.SH AUTHOR
nx was written by Benedikt Boehm <hollow@gentoo.org>

You will find the newest version of dx in the libvserver package at \fBhttp://linux-vserver.org\f1. There is also a mailing list, you will find information about it at Linux-VServer main site.
.SH BUGS
You should report them to the mailing list.
.SH SEE ALSO
\fBdx(8)\f1, \fBix(8)\f1, \fBns(8)\f1, \fBvr(8)\f1, \fBvx(8)\f1, 
